In [1]:
import pandas as pd
import os

In [4]:
path = "/mnt/aimm/scratch/jwenckst/virtues/virtues_public/assets/example_dataset"
tid = 'cords2024cancer_ocmzljpb_0001'

In [ ]:
tissues = pd.read_parquet(os.path.join(path, "metadata/tissues.parquet"))
tissues.query("tissue_id == @tid").reset_index().to_parquet(os.path.join(path, "metadata/tissues.parquet"))

In [16]:
cells = pd.read_parquet(os.path.join(path, "metadata/cells.parquet"))
cells.query("tissue_id == @tid").reset_index().to_parquet(os.path.join(path, "metadata/cells.parquet"))

In [ ]:
channels_per_tissue = pd.read_parquet(os.path.join(path, "imc/channels_per_tissue.parquet"))
channels_per_tissue[channels_per_tissue.index == tid].to_parquet(os.path.join(path, "imc/channels_per_tissue.parquet"))

In [ ]:
means = pd.read_parquet(os.path.join(path, "imc/1_0mpp/standardization/quantile_clipping_log1p/uq_0.99_image/global_level_means.parquet"))
stds = pd.read_parquet(os.path.join(path, "imc/1_0mpp/standardization/quantile_clipping_log1p/uq_0.99_image/global_level_stds.parquet"))
quantiles = pd.read_parquet(os.path.join(path, "imc/1_0mpp/standardization/quantile_clipping_log1p/uq_0.99_image/image_level_upper_quantiles.parquet"))

,MPO,S100,SMA,H3,FAP,HLA-DR,CD146,CDH11,CA9,Collagen I+Fibronectin,...,CD31+vWF,CXCL12,CCL21,panCK,CDH6,Iridium,Iridium (V2),Ki-67,CAV1,CD15
0,0.08864,0.212803,0.458729,0.720679,0.405588,0.670341,0.287218,0.22316,0.254125,0.611851,...,0.298414,0.139764,0.054327,1.380625,0.088818,3.260845,3.780947,0.384948,0.55073,0.927556

In [ ]:
quantiles[quantiles.index == tid].to_parquet(os.path.join(path, "imc/1_0mpp/standardization/quantile_clipping_log1p/uq_0.99_image/image_level_upper_quantiles.parquet"))

,MPO,S100,SMA,H3,FAP,HLA-DR,CD146,CDH11,CA9,Collagen I+Fibronectin,...,CD31+vWF,CXCL12,CCL21,panCK,CDH6,Iridium,Iridium (V2),Ki-67,CAV1,CD15
cords2024cancer_ocmzljpb_0001,4.963758,3.080627,31.751657,10.402661,9.776495,23.319841,8.066498,4.086049,4.795215,21.314684,...,5.949944,3.558238,2.0,99.110817,2.0,648.422729,1145.201538,4.708613,6.333565,83.561348

In [5]:
tile_coords = pd.read_parquet(os.path.join(path, "tiling/1_0mpp/default/128_tile_coordinates.parquet"))

In [7]:
tile_coords.query("tissue_id == @tid").reset_index().to_parquet(os.path.join(path, "tiling/1_0mpp/default/128_tile_coordinates.parquet"))

In [8]:
tile_stats = pd.read_parquet(os.path.join(path, "tiling/1_0mpp/default/128_tile_stats.parquet"))

In [10]:
tile_stats[tile_stats.index == tid].to_parquet(os.path.join(path, "tiling/1_0mpp/default/128_tile_stats.parquet"))